---
DEPLOYMENT_PLAYBOOKS: https://github.com/poanetwork/deployment-playbooks.git
DEPLOYMENT_TERRAFORM: https://github.com/poanetwork/deployment-terraform.git
DEPLOYMENT_PLAYBOOKS_BRANCH: master
DEPLOYMENT_TERRAFORM_BRANCH: master
C4COIN_CONSENSUS_CONTRACTS: https://github.com/c4coin/c4coin-network-consensus-contracts.git
C4COIN_CONSENSUS_CONTRACTS_BRANCH: "alphanet"
terraform_version: 0.11.7
node_version: 8
moc_secret_length: 20
netstat_secret_length: 20
cert_secret_length: 20
MOC_SECRET: ""
CERT_SECRET: ""
NETSTAT_SECRET: ""
MOC_ADDRESS: ""
